# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalcurrency-countrydata-deployment 
  labels:
    app: globalcurrency-countrydata 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: globalcurrency-countrydata 
  template:
    metadata:
      labels:
        app: globalcurrency-countrydata 
    spec:
      containers:
      - name: globalcurrency-countrydata-app 
        image: 515966505061.dkr.ecr.eu-west-1.amazonaws.com/globalcurrency-countrydata-app
        ports:
        - containerPort: 3000 
