apiVersion: v1
kind: Service
metadata:
  name: globalcurrency-countrydata-service 
  labels:
    app: globalcurrency-countrydata 
spec:
  selector:
    app: globalcurrency-countrydata 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
  type: LoadBalancer # This will provision an AWS LoadBalancer
