name: CI/CD Pipeline to EKS

on:
  push:
    branches: [ main ] # Triggers on push to the main branch
  pull_request:
    branches: [ main ] # Triggers on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Uses a GitHub-hosted Ubuntu runner

    permissions:
      id-token: write # Required for aws-actions/configure-aws-credentials with OIDC
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Checks out your repository's code into the runner's workspace

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 # Your AWS region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} # Your ECR repository name (e.g., globalcurrency-countrydata-app)
        IMAGE_TAG: ${{ github.sha }} # Use commit SHA as image tag for uniqueness
      run: |
        echo "Building Docker image at $(date)..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest # Also tag as latest
        echo "Docker image built and tagged at $(date)."

        echo "Pushing Docker image to ECR at $(date)..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image pushed to ECR at $(date)."

    - name: Update Kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name globalcurrency-countrydata-cluster --region eu-west-1
        echo "Kubeconfig updated for EKS cluster at $(date)."

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Applying Kubernetes manifests to EKS at $(date)..."
        # Update the image in your deployment.yml to use the ECR image
        # This assumes your deployment.yml has a container named 'globalcurrency-countrydata-app'
        kubectl set image deployment/globalcurrency-countrydata-deployment globalcurrency-countrydata-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --record
        echo "Kubernetes deployment image updated at $(date)."

        echo "Applying Kubernetes service manifest to EKS (type LoadBalancer) at $(date)..."
        kubectl apply -f service.yml
        echo "Kubernetes service manifest applied at $(date)."

        echo "Waiting for globalcurrency-countrydata deployment to be ready at $(date)..."
        kubectl rollout status deployment/globalcurrency-countrydata-deployment
        echo "Deployment rollout complete at $(date)."

        echo "Getting EKS LoadBalancer URL at $(date)..."
        # Wait for the LoadBalancer to be provisioned and get its external IP
        LB_HOSTNAME=""
        for i in $(seq 1 30); do # Try for up to 5 minutes (30 * 10 seconds)
          LB_HOSTNAME=$(kubectl get service globalcurrency-countrydata-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [ -n "$LB_HOSTNAME" ]; then
            echo "LoadBalancer hostname found: $LB_HOSTNAME"
            break
          fi
          echo "Waiting for LoadBalancer hostname... ($i/30)"
          sleep 10
        done

        if [ -z "$LB_HOSTNAME" ]; then
          echo "ERROR: LoadBalancer hostname not found after timeout."
          exit 1
        fi

        echo "EKS LoadBalancer URL: http://$LB_HOSTNAME"
        echo "Deployment to EKS successful at $(date)!"